image: registry.cn-hangzhou.aliyuncs.com/tsa-tools/java-ci:8

stages:
- mvn-package
- mvn-deploy
- docker-build

maven-package-build:
  stage: mvn-package
  script:
  - mvn package -U -DskipTests=false
  - mkdir -p /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
  - cp svc/target/app.jar /cache/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}/app.jar

maven-package-deploy:
  stage: mvn-deploy
  script:
  - mvn clean deploy -DskipTests
  only:
  - master

docker-build:
  stage: docker-build
  script:
  - docker_build
  - chart_build
  only:
  - tags
  - /^hotfix-.*$/
  - /^release-.*$/

.auto_devops: &auto_devops |
  curl -o .auto_devops.sh \
      "${MINERVA_URL}/devops/ci?token=${Token}&type=microservice"
  if [ $? -ne 0 ];then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
- *auto_devops
